from fastapi import APIRouter, Depends, HTTPException
from core.rbac import require_permission
from core.utils import normalize_station_id
from db.mongo import get_assets_3d_col, get_asset_status_col, get_evacuation_routes_col
from bson import ObjectId

router = APIRouter(prefix="/twin", tags=["Digital Twin"])

def base_response(data):
    if isinstance(data, dict):
        data["dataSource"] = "simulation_engine"
        data["isSimulation"] = True
        data["dataDisclaimer"] = "This data is generated by a simulation engine for demonstration purposes only. Not representative of real NCPOR station telemetry."
    return data

@router.get("/{station_id}/layout")
async def get_layout(station_id: str, current_user: dict = Depends(require_permission("VIEW_DIGITAL_TWIN"))):
    sid = normalize_station_id(station_id)
    col = get_assets_3d_col()
    assets = await col.find({"station_id": sid}).to_list(length=None)
    for a in assets: a["_id"] = str(a["_id"])
    return base_response({"assets": assets})

@router.get("/{station_id}/overlay")
async def get_overlay(station_id: str, current_user: dict = Depends(require_permission("VIEW_DIGITAL_TWIN"))):
    sid = normalize_station_id(station_id)
    col = get_asset_status_col()
    statuses = await col.find({"station_id": sid}).to_list(length=None)
    for s in statuses: s["_id"] = str(s["_id"])
    return base_response({"statuses": statuses})

@router.get("/assets/{asset_id}")
async def get_asset_detail(asset_id: str, current_user: dict = Depends(require_permission("VIEW_DIGITAL_TWIN"))):
    col = get_assets_3d_col()
    try:
        query = {"_id": ObjectId(asset_id)}
    except Exception:
        query = {"asset_id": asset_id}
    asset = await col.find_one(query)
    if not asset: raise HTTPException(404, detail="Asset not found")
    asset["_id"] = str(asset["_id"])
    return base_response({"asset": asset})

@router.get("/{station_id}/evacuation")
async def get_twin_evacuation(station_id: str, current_user: dict = Depends(require_permission("VIEW_DIGITAL_TWIN"))):
    sid = normalize_station_id(station_id)
    col = get_evacuation_routes_col()
    routes = await col.find({"station_id": sid}).to_list(length=None)
    for r in routes: r["_id"] = str(r["_id"])
    return base_response({"routes": routes})
