from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Optional
from core.rbac import require_permission
from core.utils import normalize_station_id
from db.mongo import get_incidents_col, get_muster_col, get_evacuation_routes_col
from services.audit_service import log_action
from ws.incident_ws import broadcast_incident
from datetime import datetime
from bson import ObjectId

router = APIRouter(tags=["Emergency"])

class IncidentTrigger(BaseModel):
    station_id: str
    type: str
    severity: str
    description: str
    location: Optional[str] = None

def base_response(data):
    if isinstance(data, dict):
        data["dataSource"] = "simulation_engine"
        data["isSimulation"] = True
        data["dataDisclaimer"] = "This data is generated by a simulation engine for demonstration purposes only. Not representative of real NCPOR station telemetry."
    return data

@router.get("/stations/{station_id}/incidents")
@router.get("/stations/{station_id}/emergency/incidents")
async def get_incidents(station_id: str, current_user: dict = Depends(require_permission("VIEW_EMERGENCY"))):
    sid = normalize_station_id(station_id)
    col = get_incidents_col()
    incidents = await col.find({"station_id": sid}).to_list(length=None)
    for i in incidents: i["_id"] = str(i["_id"])
    return base_response({"incidents": incidents})

@router.post("/emergency/trigger")
@router.post("/emergency/incidents")
async def trigger_incident(req: IncidentTrigger, current_user: dict = Depends(require_permission("TRIGGER_INCIDENT"))):
    sid = normalize_station_id(req.station_id)
    col = get_incidents_col()
    existing = await col.find_one({"station_id": sid, "type": req.type, "status": "ACTIVE"})
    
    if existing:
        return base_response({"status": "already_active", "incident_id": str(existing["_id"])})
        
    incident = {
        "station_id": sid,
        "type": req.type,
        "severity": req.severity,
        "description": req.description,
        "location": req.location or "Main Facility",
        "status": "ACTIVE",
        "escalation_level": 2 if req.severity == "HIGH" else 1,
        "timeline": [{"event": "Incident triggered", "timestamp": datetime.utcnow(), "author": current_user["email"]}],
        "created_at": datetime.utcnow()
    }
    
    result = await col.insert_one(incident)
    incident["_id"] = str(result.inserted_id)
    
    await log_action(str(current_user["_id"]), current_user["role"], "TRIGGER_INCIDENT", incident["_id"], "SUCCESS")
    await broadcast_incident(sid, incident)
    
    return base_response({"status": "triggered", "incident": incident, "incident_id": incident["_id"]})

@router.post("/incidents/{incident_id}/escalate")
@router.put("/emergency/incidents/{incident_id}/escalate")
async def escalate_incident(incident_id: str, current_user: dict = Depends(require_permission("ACK_INCIDENT"))):
    col = get_incidents_col()
    try:
        query = {"_id": ObjectId(incident_id)}
    except Exception:
        query = {"incident_id": incident_id}
        
    incident = await col.find_one(query)
    if not incident: raise HTTPException(404, detail="Incident not found")
    
    new_level = incident.get("escalation_level", 1) + 1
    event = {"event": f"Escalated to level {new_level}", "timestamp": datetime.utcnow(), "author": current_user["email"]}
    
    await col.update_one(
        query,
        {"$set": {"escalation_level": new_level}, "$push": {"timeline": event}}
    )
    
    await log_action(str(current_user["_id"]), current_user["role"], "ESCALATE_INCIDENT", str(incident["_id"]), "SUCCESS")
    
    incident["escalation_level"] = new_level
    incident["timeline"].append(event)
    incident["_id"] = str(incident["_id"])
    await broadcast_incident(incident["station_id"], incident)
    
    return base_response({"status": "escalated", "incident": incident})

@router.post("/incidents/{incident_id}/resolve")
@router.put("/emergency/incidents/{incident_id}/resolve")
async def resolve_incident(incident_id: str, current_user: dict = Depends(require_permission("ACK_INCIDENT"))):
    col = get_incidents_col()
    try:
        query = {"_id": ObjectId(incident_id)}
    except Exception:
        query = {"incident_id": incident_id}
        
    incident = await col.find_one(query)
    if not incident: raise HTTPException(404, detail="Incident not found")
    
    event = {"event": "Incident resolved", "timestamp": datetime.utcnow(), "author": current_user["email"]}
    await col.update_one(
        query,
        {"$set": {"status": "RESOLVED"}, "$push": {"timeline": event}}
    )
    
    await log_action(str(current_user["_id"]), current_user["role"], "RESOLVE_INCIDENT", str(incident["_id"]), "SUCCESS")
    return base_response({"status": "resolved"})

@router.get("/stations/{station_id}/muster")
@router.get("/stations/{station_id}/emergency/muster")
async def get_muster(station_id: str, current_user: dict = Depends(require_permission("VIEW_EMERGENCY"))):
    sid = normalize_station_id(station_id)
    col = get_muster_col()
    muster = await col.find({"station_id": sid}).to_list(length=None)
    for m in muster: m["_id"] = str(m["_id"])
    return base_response({"muster_roll": muster, "muster": muster})

@router.post("/muster/{crew_id}/safe")
@router.put("/emergency/muster/{crew_id}/safe")
async def mark_safe(crew_id: str, current_user: dict = Depends(require_permission("ACK_INCIDENT"))):
    col = get_muster_col()
    await col.update_one({"$or": [{"personnel_id": crew_id}, {"crew_id": crew_id}]}, {"$set": {"status": "SAFE", "updated_at": datetime.utcnow()}})
    await log_action(str(current_user["_id"]), current_user["role"], "MARK_SAFE", crew_id, "SUCCESS")
    return base_response({"status": "safe"})

@router.get("/stations/{station_id}/evacuation")
@router.get("/stations/{station_id}/emergency/evacuation-routes")
async def get_evacuation(station_id: str, current_user: dict = Depends(require_permission("VIEW_EMERGENCY"))):
    sid = normalize_station_id(station_id)
    col = get_evacuation_routes_col()
    routes = await col.find({"station_id": sid}).to_list(length=None)
    for r in routes: r["_id"] = str(r["_id"])
    return base_response({"routes": routes, "evacuation_routes": routes})
