from fastapi import APIRouter, Depends
from core.rbac import require_permission
from core.utils import normalize_station_id
from db.mongo import get_weather_col, get_hazard_thresholds_col
from simulators.environment_simulator import get_latest_weather
from engines.environment_engine import calculate_weather_trend, check_hazard_conditions, generate_pre_incident_advisory

router = APIRouter(prefix="/stations/{station_id}/environment", tags=["Environment"])

def base_response(data):
    if isinstance(data, dict):
        data["dataSource"] = "simulation_engine"
        data["isSimulation"] = True
        data["dataDisclaimer"] = "This data is generated by a simulation engine for demonstration purposes only. Not representative of real NCPOR station telemetry."
    return data

@router.get("/weather")
async def get_weather(station_id: str, current_user: dict = Depends(require_permission("VIEW_ENVIRONMENT"))):
    sid = normalize_station_id(station_id)
    latest = get_latest_weather(sid)
    return base_response({"weather": latest})

@router.get("/trend")
@router.get("/weather/history")
async def get_trend(station_id: str, hours: int = 48, current_user: dict = Depends(require_permission("VIEW_ENVIRONMENT"))):
    sid = normalize_station_id(station_id)
    col = get_weather_col()
    history = await col.find({"station_id": sid}).sort("timestamp", -1).limit(hours).to_list(length=None)
    trend = calculate_weather_trend(history)
    for h in history: h["_id"] = str(h["_id"])
    return base_response({"trend": trend, "history": history})

@router.get("/hazards")
async def get_hazards(station_id: str, current_user: dict = Depends(require_permission("VIEW_ENVIRONMENT"))):
    sid = normalize_station_id(station_id)
    latest = get_latest_weather(sid)
    col = get_hazard_thresholds_col()
    thresholds = await col.find({"station_id": sid}).to_list(length=None)
    
    hazards = check_hazard_conditions(latest, thresholds)
    advisory = generate_pre_incident_advisory(hazards)
    
    return base_response({"hazards": hazards, "advisory": advisory})
