from fastapi import APIRouter, Depends
from core.rbac import require_permission
from core.utils import normalize_station_id
from db.mongo import get_resupply_col, get_inventory_col
from engines.logistics_engine import calculate_days_remaining, assess_resupply_urgency
from simulators.environment_simulator import get_latest_weather
from simulators.logistics_simulator import get_transport_window
from engines.energy_engine import calculate_resource_burn_rates

router = APIRouter(prefix="/stations/{station_id}/logistics", tags=["Logistics"])

def base_response(data):
    if isinstance(data, dict):
        data["dataSource"] = "simulation_engine"
        data["isSimulation"] = True
        data["dataDisclaimer"] = "This data is generated by a simulation engine for demonstration purposes only. Not representative of real NCPOR station telemetry."
    return data

@router.get("/resupply")
@router.get("/shipments")
async def get_resupply_schedule(station_id: str, current_user: dict = Depends(require_permission("VIEW_LOGISTICS"))):
    sid = normalize_station_id(station_id)
    col = get_resupply_col()
    schedule = await col.find({"station_id": sid}).to_list(length=None)
    for s in schedule: s["_id"] = str(s["_id"])
    return base_response({"schedule": schedule, "shipments": schedule})

@router.get("/inventory")
async def get_inventory(station_id: str, current_user: dict = Depends(require_permission("VIEW_LOGISTICS"))):
    sid = normalize_station_id(station_id)
    col = get_inventory_col()
    inventory = await col.find({"station_id": sid}).to_list(length=None)
    
    burn_rates = calculate_resource_burn_rates([])
    inventory_with_days = calculate_days_remaining(inventory, burn_rates)
    
    return base_response({"inventory": inventory_with_days})

@router.get("/transport-window")
@router.get("/transport-windows")
async def get_window(station_id: str, current_user: dict = Depends(require_permission("VIEW_LOGISTICS"))):
    sid = normalize_station_id(station_id)
    weather = get_latest_weather(sid)
    window = get_transport_window(sid, weather)
    return base_response({"transport_window": window, "transport_windows": window})

@router.get("/summary")
async def get_summary(station_id: str, current_user: dict = Depends(require_permission("VIEW_LOGISTICS"))):
    sid = normalize_station_id(station_id)
    col = get_inventory_col()
    inventory = await col.find({"station_id": sid}).to_list(length=None)
    
    burn_rates = calculate_resource_burn_rates([])
    inventory_with_days = calculate_days_remaining(inventory, burn_rates)
    urgency = assess_resupply_urgency(inventory_with_days)
    
    return base_response({
        "urgency": urgency,
        "critical_count": len(urgency.get("critical_items", [])),
        "warning_count": len(urgency.get("warning_items", []))
    })
