from fastapi import APIRouter, Depends
from core.rbac import require_permission
from core.utils import normalize_station_id
from db.mongo import get_personnel_col, get_shift_schedule_col
from engines.personnel_engine import calculate_operational_readiness, get_shift_coverage

router = APIRouter(prefix="/stations/{station_id}/personnel", tags=["Personnel"])

def base_response(data):
    if isinstance(data, dict):
        data["dataSource"] = "simulation_engine"
        data["isSimulation"] = True
        data["dataDisclaimer"] = "This data is generated by a simulation engine for demonstration purposes only. Not representative of real NCPOR station telemetry."
    return data

@router.get("")
async def get_personnel(station_id: str, current_user: dict = Depends(require_permission("VIEW_PERSONNEL"))):
    sid = normalize_station_id(station_id)
    col = get_personnel_col()
    personnel = await col.find({"station_id": sid}).to_list(length=None)
    for p in personnel: p["_id"] = str(p["_id"])
    return base_response({"personnel": personnel})

@router.get("/summary")
async def get_summary(station_id: str, current_user: dict = Depends(require_permission("VIEW_PERSONNEL"))):
    sid = normalize_station_id(station_id)
    col = get_personnel_col()
    personnel = await col.find({"station_id": sid}).to_list(length=None)
    readiness = calculate_operational_readiness(personnel)
    return base_response({"readiness": readiness, "summary": readiness})

@router.get("/shifts")
async def get_shifts(station_id: str, current_user: dict = Depends(require_permission("VIEW_PERSONNEL"))):
    sid = normalize_station_id(station_id)
    col = get_shift_schedule_col()
    shifts = await col.find({"station_id": sid}).to_list(length=None)
    for s in shifts: s["_id"] = str(s["_id"])
    return base_response({"shifts": shifts})
