from fastapi import APIRouter, Depends
from pydantic import BaseModel
from typing import Optional, List
from core.rbac import require_permission
from core.utils import normalize_station_id
from db.mongo import get_sop_documents_col, get_ai_chat_logs_col
from services.rag_service import rag_service
from services.llm_service import llm_service
from datetime import datetime

router = APIRouter(tags=["Polar AI"])

class ChatRequest(BaseModel):
    question: Optional[str] = None
    message: Optional[str] = None
    station_id: Optional[str] = "maitri"
    session_id: Optional[str] = "default-session"
    history: Optional[List[dict]] = None

def base_response(data):
    if isinstance(data, dict):
        data["dataSource"] = "simulation_engine"
        data["isSimulation"] = True
        data["dataDisclaimer"] = "This data is generated by a simulation engine for demonstration purposes only. Not representative of real NCPOR station telemetry."
    return data

@router.post("/polar-ai/chat")
@router.post("/ai/chat")
async def chat(req: ChatRequest, current_user: dict = Depends(require_permission("USE_POLAR_AI"))):
    sid = normalize_station_id(req.station_id)
    query = req.question or req.message or "What is the station emergency status?"
    sop_col = get_sop_documents_col()
    context_chunks = await rag_service.get_context_for_query(query, sid, sop_col)
    
    station_context = {"station_id": sid}
    response = await llm_service.chat(query, context_chunks, station_context)
    
    log_col = get_ai_chat_logs_col()
    await log_col.insert_one({
        "session_id": req.session_id or "default",
        "user_id": str(current_user["_id"]),
        "station_id": sid,
        "question": query,
        "response": response["answer"],
        "timestamp": datetime.utcnow()
    })
    
    return base_response(response)

@router.get("/polar-ai/suggestions")
@router.get("/ai/suggestions")
async def get_suggestions(station_id: Optional[str] = "maitri", current_user: dict = Depends(require_permission("USE_POLAR_AI"))):
    suggestions = [
        "What is the SOP for a generator failure in Winter?",
        "How do I handle a fuel leak emergency?",
        "What is the blizzard safety & whiteout protocol?",
        "What are the medical evacuation procedures?"
    ]
    return base_response({"suggestions": suggestions})

@router.get("/polar-ai/health")
@router.get("/ai/health")
async def check_health(current_user: dict = Depends(require_permission("USE_POLAR_AI"))):
    health = await llm_service.health_check()
    return base_response(health)
