from fastapi import APIRouter, Depends, HTTPException
from core.rbac import require_permission
from core.utils import normalize_station_id
from db.mongo import get_access_points_col, get_access_events_col, get_personnel_col
from engines.security_engine import calculate_security_risk, correlate_field_personnel

router = APIRouter(prefix="/stations/{station_id}/security", tags=["Security"])

def base_response(data):
    if isinstance(data, dict):
        data["dataSource"] = "simulation_engine"
        data["isSimulation"] = True
        data["dataDisclaimer"] = "This data is generated by a simulation engine for demonstration purposes only. Not representative of real NCPOR station telemetry."
    return data

@router.get("")
@router.get("/access-points")
@router.get("/risk")
async def get_security_status(station_id: str, current_user: dict = Depends(require_permission("VIEW_SECURITY"))):
    sid = normalize_station_id(station_id)
    col = get_access_points_col()
    points = await col.find({"station_id": sid}).to_list(length=None)
    for p in points: p["_id"] = str(p["_id"])
    
    events_col = get_access_events_col()
    recent_events = await events_col.find({"station_id": sid}).sort("timestamp", -1).limit(50).to_list(length=None)
    
    risk = calculate_security_risk(points, recent_events)
    return base_response({"access_points": points, "points": points, "risk_assessment": risk, "risk": risk})

@router.get("/events")
async def get_security_events(station_id: str, limit: int = 50, current_user: dict = Depends(require_permission("VIEW_SECURITY"))):
    sid = normalize_station_id(station_id)
    col = get_access_events_col()
    events = await col.find({"station_id": sid}).sort("timestamp", -1).limit(limit).to_list(length=None)
    for e in events: e["_id"] = str(e["_id"])
    return base_response({"events": events})

@router.get("/field-correlation")
async def get_field_correlation(station_id: str, current_user: dict = Depends(require_permission("VIEW_SECURITY"))):
    sid = normalize_station_id(station_id)
    p_col = get_personnel_col()
    field_personnel = await p_col.find({"station_id": sid, "status": "IN_FIELD_OPS"}).to_list(length=None)
    
    e_col = get_access_events_col()
    events = await e_col.find({"station_id": sid}).to_list(length=None)
    
    correlated = correlate_field_personnel(events, field_personnel)
    return base_response({"field_teams": correlated, "field_personnel": correlated})
