from fastapi import APIRouter, Depends, HTTPException
from core.rbac import require_permission
from core.utils import normalize_station_id
from db.mongo import get_stations_col, get_telemetry_col
from engines.energy_engine import calculate_health_index, detect_anomalies, calculate_whatif, calculate_resource_burn_rates, generate_ai_mission_report
from simulators.telemetry_simulator import get_latest_telemetry

router = APIRouter(prefix="/stations", tags=["Stations"])

def base_response(data):
    if isinstance(data, dict):
        data["dataSource"] = "simulation_engine"
        data["isSimulation"] = True
        data["dataDisclaimer"] = "This data is generated by a simulation engine for demonstration purposes only. Not representative of real NCPOR station telemetry."
    return data

@router.get("")
async def list_stations():
    col = get_stations_col()
    stations = await col.find({}).to_list(length=None)
    for s in stations:
        s["_id"] = str(s["_id"])
    return base_response({"stations": stations})

@router.get("/{station_id}")
async def get_station(station_id: str):
    sid = normalize_station_id(station_id)
    col = get_stations_col()
    station = await col.find_one({"$or": [{"station_id": sid}, {"station_id": station_id}]})
    if not station:
        raise HTTPException(status_code=404, detail="Station not found")
    station["_id"] = str(station["_id"])
    return base_response(station)

@router.get("/{station_id}/telemetry")
async def get_station_telemetry(station_id: str, current_user: dict = Depends(require_permission("VIEW_DASHBOARD"))):
    sid = normalize_station_id(station_id)
    latest = get_latest_telemetry(sid)
    history_col = get_telemetry_col()
    history = await history_col.find({"station_id": sid}).sort("timestamp", -1).limit(10).to_list(length=None)
    
    health = calculate_health_index(latest)
    anomalies = detect_anomalies(history)
    burn_rates = calculate_resource_burn_rates(history)
    
    return base_response({
        "telemetry": latest,
        "health_index": health,
        "anomalies": anomalies,
        "burn_rates": burn_rates
    })

@router.get("/{station_id}/telemetry/history")
async def get_telemetry_history(station_id: str, hours: int = 24, current_user: dict = Depends(require_permission("VIEW_DASHBOARD"))):
    sid = normalize_station_id(station_id)
    col = get_telemetry_col()
    history = await col.find({"station_id": sid}).sort("timestamp", -1).limit(hours * 12).to_list(length=None)
    for h in history: h["_id"] = str(h["_id"])
    return base_response({"history": history})

@router.post("/{station_id}/telemetry/whatif")
async def simulation_whatif(station_id: str, adjustments: dict, current_user: dict = Depends(require_permission("VIEW_DASHBOARD"))):
    sid = normalize_station_id(station_id)
    latest = get_latest_telemetry(sid)
    result = calculate_whatif(latest, adjustments)
    return base_response(result)

@router.get("/{station_id}/telemetry/report")
async def get_mission_report(station_id: str, current_user: dict = Depends(require_permission("VIEW_DASHBOARD"))):
    sid = normalize_station_id(station_id)
    latest = get_latest_telemetry(sid)
    health = calculate_health_index(latest)
    history = await get_telemetry_col().find({"station_id": sid}).sort("timestamp", -1).limit(10).to_list(length=None)
    anomalies = detect_anomalies(history)
    
    report = generate_ai_mission_report(latest, health, anomalies)
    return base_response(report)
