"""
Energy Engine — all derived value logic for Module 1.
This is the single source of truth for energy calculations.
No duplicate logic in frontend or in any other module.
"""
from typing import Optional
import math


DATA_DISCLAIMER = (
    "This data is generated by a simulation engine for demonstration purposes only. "
    "Not representative of real NCPOR station telemetry."
)


def calculate_health_index(telemetry: dict) -> dict:
    """
    Compute composite energy health index (0-100) with letter grade.
    Weights: renewable_ratio 30%, fuel_level 25%, load_balance 25%, consumables 20%
    """
    solar_kw = telemetry.get("solar_kw", 0.0)
    wind_kw = telemetry.get("wind_kw", 0.0)
    diesel_kw = telemetry.get("diesel_kw", 0.0)
    load_kw = max(telemetry.get("load_kw", 1.0), 1.0)
    fuel_pct = telemetry.get("fuel_pct", 0.0)
    water_pct = telemetry.get("water_pct", 100.0)
    food_pct = telemetry.get("food_pct", 100.0)
    consumables_pct = telemetry.get("consumables_pct", 100.0)

    # Renewable ratio score: what fraction of load is covered by renewables
    renewable_kw = solar_kw + wind_kw
    renewable_ratio = min(renewable_kw / load_kw, 1.0)
    renewable_score = renewable_ratio * 100.0

    # Fuel score: direct percentage, but penalised steeply below 30%
    if fuel_pct >= 30:
        fuel_score = fuel_pct
    elif fuel_pct >= 20:
        fuel_score = 20 + (fuel_pct - 20) * 0.5
    else:
        fuel_score = fuel_pct * 0.5  # critical degradation
    fuel_score = max(0.0, min(100.0, fuel_score))

    # Load balance score: penalise if load exceeds total generation
    total_gen = solar_kw + wind_kw + diesel_kw
    if load_kw <= total_gen:
        load_balance_score = 100.0
    else:
        deficit_pct = (load_kw - total_gen) / load_kw * 100
        load_balance_score = max(0.0, 100.0 - deficit_pct * 2)

    # Consumables score: minimum of the three consumable categories
    consumables_score = min(water_pct, food_pct, consumables_pct)

    score = (
        renewable_score * 0.30
        + fuel_score * 0.25
        + load_balance_score * 0.25
        + consumables_score * 0.20
    )
    score = round(max(0.0, min(100.0, score)), 2)

    if score >= 80:
        grade, grade_desc = "A", "Excellent"
    elif score >= 65:
        grade, grade_desc = "B", "Good"
    elif score >= 50:
        grade, grade_desc = "C", "Fair"
    elif score >= 35:
        grade, grade_desc = "D", "Poor"
    else:
        grade, grade_desc = "F", "Critical"

    # Generate human-readable reason
    weak_factors = []
    if renewable_score < 40:
        weak_factors.append("low renewable generation")
    if fuel_score < 50:
        weak_factors.append(f"fuel at {fuel_pct:.1f}% (critical level)")
    if load_balance_score < 80:
        weak_factors.append("load exceeding generation capacity")
    if consumables_score < 50:
        weak_factors.append("consumables running low")

    if weak_factors:
        reason = f"Score degraded by: {', '.join(weak_factors)}."
    else:
        reason = "All energy systems operating within acceptable parameters."

    return {
        "score": score,
        "grade": grade,
        "grade_description": grade_desc,
        "factors": [
            {"name": "Renewable Ratio", "value": round(renewable_ratio * 100, 1), "score": round(renewable_score, 2), "weight": 30, "unit": "%"},
            {"name": "Fuel Level", "value": round(fuel_pct, 1), "score": round(fuel_score, 2), "weight": 25, "unit": "%"},
            {"name": "Load Balance", "value": round(load_kw, 1), "score": round(load_balance_score, 2), "weight": 25, "unit": "kW"},
            {"name": "Consumables", "value": round(consumables_score, 1), "score": round(consumables_score, 2), "weight": 20, "unit": "%"},
        ],
        "reason": reason,
    }


def detect_anomalies(history: list[dict]) -> list[dict]:
    """
    Detect anomalies from telemetry history.
    Returns list of {metric, type, value, threshold, severity, message}.
    """
    if not history:
        return []

    anomalies = []
    latest = history[0]

    # --- Fuel critical ---
    fuel_pct = latest.get("fuel_pct", 100)
    if fuel_pct < 20:
        anomalies.append({
            "metric": "fuel_pct", "type": "critical_low",
            "value": fuel_pct, "threshold": 20,
            "severity": "HIGH", "message": f"Fuel at {fuel_pct:.1f}% — CRITICAL. Immediate resupply required."
        })
    elif fuel_pct < 35:
        anomalies.append({
            "metric": "fuel_pct", "type": "low",
            "value": fuel_pct, "threshold": 35,
            "severity": "MEDIUM", "message": f"Fuel at {fuel_pct:.1f}% — approaching critical level."
        })

    # --- Fuel sudden drop (compare last 2 readings) ---
    if len(history) >= 2:
        prev_fuel = history[1].get("fuel_pct", fuel_pct)
        drop = prev_fuel - fuel_pct
        if drop > 5:
            anomalies.append({
                "metric": "fuel_pct", "type": "sudden_drop",
                "value": fuel_pct, "threshold": prev_fuel - 5,
                "severity": "HIGH", "message": f"Fuel dropped {drop:.1f}% in last interval — possible leak or surge usage."
            })

    # --- Load spike ---
    if len(history) >= 5:
        avg_load = sum(r.get("load_kw", 0) for r in history[1:5]) / 4
        curr_load = latest.get("load_kw", 0)
        if avg_load > 0 and curr_load > avg_load * 1.25:
            anomalies.append({
                "metric": "load_kw", "type": "spike",
                "value": round(curr_load, 2), "threshold": round(avg_load * 1.25, 2),
                "severity": "MEDIUM",
                "message": f"Power load {curr_load:.1f} kW is {((curr_load/avg_load)-1)*100:.0f}% above recent average ({avg_load:.1f} kW)."
            })

    # --- Renewable dropout ---
    solar = latest.get("solar_kw", 0)
    wind = latest.get("wind_kw", 0)
    hour = latest.get("timestamp", {})
    # Check if during daylight hours solar is unexpectedly zero
    if isinstance(latest.get("timestamp"), str):
        try:
            from datetime import datetime
            dt = datetime.fromisoformat(latest["timestamp"].replace("Z", ""))
            if 8 <= dt.hour <= 16 and solar < 1:
                anomalies.append({
                    "metric": "solar_kw", "type": "dropout",
                    "value": solar, "threshold": 5,
                    "severity": "MEDIUM",
                    "message": "Solar panels generating <1 kW during expected daylight hours. Possible panel issue or cloud/snow cover."
                })
        except Exception:
            pass

    # --- Water low ---
    water_pct = latest.get("water_pct", 100)
    if water_pct < 30:
        anomalies.append({
            "metric": "water_pct", "type": "critical_low",
            "value": water_pct, "threshold": 30,
            "severity": "HIGH", "message": f"Fresh water reserve at {water_pct:.1f}% — critical."
        })

    return anomalies


def calculate_whatif(telemetry: dict, adjustments: dict) -> dict:
    """
    Project outcomes given hypothetical operational adjustments.
    adjustments: {solar_multiplier, wind_multiplier, load_reduction_pct, diesel_reduction_pct}
    Returns: {fuel_saved_pct, autonomy_days_change, new_health_index, projected_telemetry, warnings}
    """
    solar_mult = float(adjustments.get("solar_multiplier", 1.0))
    wind_mult = float(adjustments.get("wind_multiplier", 1.0))
    load_reduction = float(adjustments.get("load_reduction_pct", 0.0)) / 100.0

    proj = telemetry.copy()
    proj["solar_kw"] = telemetry.get("solar_kw", 0) * solar_mult
    proj["wind_kw"] = telemetry.get("wind_kw", 0) * wind_mult
    proj["load_kw"] = telemetry.get("load_kw", 0) * (1.0 - load_reduction)

    # Recalculate diesel needed
    renewable = proj["solar_kw"] + proj["wind_kw"]
    proj["diesel_kw"] = max(0.0, proj["load_kw"] - renewable)

    # Fuel savings vs original diesel
    original_diesel = telemetry.get("diesel_kw", 0)
    diesel_saved = original_diesel - proj["diesel_kw"]
    # Each kW*hour of diesel ~ 0.0001% fuel per simulator tick
    # Express as % fuel saved per day (288 ticks @ 5s = 24h)
    fuel_saved_pct_per_day = diesel_saved * 0.0001 * 288
    autonomy_days_change = fuel_saved_pct_per_day / max(calculate_resource_burn_rates([telemetry])["fuel_burn_per_day_pct"], 0.01)

    new_health = calculate_health_index(proj)

    warnings = []
    if proj["load_kw"] < 30:
        warnings.append("Load reduction below 30 kW may affect critical life-support systems.")
    if proj["diesel_kw"] < 5 and (proj["solar_kw"] + proj["wind_kw"]) < proj["load_kw"]:
        warnings.append("Insufficient generation to meet projected load — diesel cannot be reduced this far.")

    return {
        "fuel_saved_pct_per_day": round(fuel_saved_pct_per_day, 3),
        "autonomy_days_change": round(autonomy_days_change, 1),
        "new_health_index": new_health,
        "projected_telemetry": {
            "solar_kw": round(proj["solar_kw"], 2),
            "wind_kw": round(proj["wind_kw"], 2),
            "diesel_kw": round(proj["diesel_kw"], 2),
            "load_kw": round(proj["load_kw"], 2),
        },
        "warnings": warnings,
    }


def calculate_resource_burn_rates(history: list[dict]) -> dict:
    """
    Calculate per-day burn rates from telemetry history.
    Used by logistics engine to compute days-until-resupply-needed.
    """
    if len(history) < 2:
        # Fallback defaults
        return {
            "fuel_burn_per_day_pct": 2.5,
            "water_burn_per_day_pct": 0.15,
            "food_burn_per_day_pct": 0.10,
        }

    # Take newest and oldest readings that are at least 1 hour apart
    newest = history[0]
    oldest = history[-1]

    try:
        from datetime import datetime

        def parse_ts(r):
            ts = r.get("timestamp")
            if isinstance(ts, str):
                return datetime.fromisoformat(ts.replace("Z", ""))
            return ts  # already datetime

        t_new = parse_ts(newest)
        t_old = parse_ts(oldest)
        hours = max((t_new - t_old).total_seconds() / 3600, 1.0)
        days = hours / 24.0

        fuel_drop = newest.get("fuel_pct", 70) - oldest.get("fuel_pct", 70)
        water_drop = newest.get("water_pct", 75) - oldest.get("water_pct", 75)
        food_drop = newest.get("food_pct", 80) - oldest.get("food_pct", 80)

        return {
            "fuel_burn_per_day_pct": round(abs(fuel_drop) / days, 3) if days > 0 else 2.5,
            "water_burn_per_day_pct": round(abs(water_drop) / days, 3) if days > 0 else 0.15,
            "food_burn_per_day_pct": round(abs(food_drop) / days, 3) if days > 0 else 0.10,
        }
    except Exception:
        return {
            "fuel_burn_per_day_pct": 2.5,
            "water_burn_per_day_pct": 0.15,
            "food_burn_per_day_pct": 0.10,
        }


def generate_ai_mission_report(telemetry: dict, health: dict, anomalies: list) -> dict:
    """
    Generate a deterministic AI mission report based on current station state.
    No LLM used — fully traceable logic.
    """
    score = health.get("score", 50)
    grade = health.get("grade", "C")
    fuel_pct = telemetry.get("fuel_pct", 70)
    solar_kw = telemetry.get("solar_kw", 0)
    wind_kw = telemetry.get("wind_kw", 0)
    diesel_kw = telemetry.get("diesel_kw", 0)
    load_kw = telemetry.get("load_kw", 0)
    renewable_pct = round((solar_kw + wind_kw) / max(load_kw, 1) * 100, 1)

    summary = (
        f"Station energy health is {grade} ({score}/100). "
        f"Current renewable coverage: {renewable_pct}% of load. "
        f"Diesel supplement: {diesel_kw:.1f} kW. "
        f"Fuel reserve: {fuel_pct:.1f}%. "
    )
    if score >= 80:
        summary += "All systems operating within optimal parameters."
    elif score >= 60:
        summary += "Minor inefficiencies detected — see recommendations."
    else:
        summary += "Attention required — multiple systems below optimal thresholds."

    recommendations = []
    if renewable_pct < 40:
        recommendations.append(
            f"Increase renewable utilisation — currently only {renewable_pct}% of load is covered by solar/wind. "
            "Consider shifting high-draw activities to peak solar hours (0800–1600)."
        )
    if fuel_pct < 50:
        recommendations.append(
            f"Fuel at {fuel_pct:.1f}% — schedule resupply coordination with logistics team. "
            "Target minimum 40% reserve before next resupply window."
        )
    if diesel_kw > solar_kw + wind_kw:
        recommendations.append(
            "Diesel is the primary energy source. Reduce non-essential load during low-solar periods "
            "to extend fuel autonomy."
        )
    if telemetry.get("water_pct", 100) < 60:
        recommendations.append("Fresh water reserves below 60% — initiate water conservation protocols.")
    if not recommendations:
        recommendations.append("Maintain current operational profile. No immediate action required.")

    priority_alerts = [a["message"] for a in anomalies if a.get("severity") == "HIGH"]

    return {
        "summary": summary,
        "recommendations": recommendations,
        "priority_alerts": priority_alerts,
        "data_source": "deterministic_engine",
        "isSimulation": True,
        "dataDisclaimer": DATA_DISCLAIMER,
    }
