import asyncio
import random
from datetime import datetime
from db.mongo import get_telemetry_col

telemetry_subscribers = {}

async def broadcast_telemetry(station_id: str, data: dict):
    if station_id in telemetry_subscribers:
        for queue in telemetry_subscribers[station_id]:
            await queue.put(data)

_latest_telemetry = {}

def get_latest_telemetry(station_id: str) -> dict:
    return _latest_telemetry.get(station_id, {})

async def run_telemetry_simulator():
    from core.config import settings
    while True:
        try:
            col = get_telemetry_col()
            now = datetime.utcnow()
            hour = now.hour
            
            for station_id in ["maitri", "bharati"]:
                # Solar simulation based on time of day
                solar_kw = 0
                if 6 <= hour <= 18:
                    peak = 45 if station_id == "maitri" else 35
                    solar_kw = peak * (1 - abs(12 - hour)/6.0) * random.uniform(0.8, 1.0)
                
                wind_kw = random.uniform(5, 25) if station_id == "maitri" else random.uniform(8, 25)
                load_kw = random.uniform(45, 85)
                diesel_kw = max(0, load_kw - (solar_kw + wind_kw)) + random.uniform(0, 5)
                
                prev = _latest_telemetry.get(station_id, {})
                fuel_pct = prev.get("fuel_pct", 70.0) - (diesel_kw * 0.0001)
                fuel_pct = max(15.0, fuel_pct)
                
                water_pct = prev.get("water_pct", 75.0) - 0.0005
                food_pct = prev.get("food_pct", 80.0) - 0.0003
                
                reading = {
                    "station_id": station_id,
                    "timestamp": now,
                    "solar_kw": round(solar_kw, 2),
                    "wind_kw": round(wind_kw, 2),
                    "diesel_kw": round(diesel_kw, 2),
                    "load_kw": round(load_kw, 2),
                    "fuel_pct": round(fuel_pct, 2),
                    "water_pct": round(water_pct, 2),
                    "food_pct": round(food_pct, 2),
                    "dataSource": "simulation_engine",
                    "isSimulation": True,
                    "dataDisclaimer": "This data is generated by a simulation engine for demonstration purposes only. Not representative of real NCPOR station telemetry."
                }
                
                await col.insert_one(reading.copy())
                if "_id" in reading: reading["_id"] = str(reading["_id"])
                
                _latest_telemetry[station_id] = reading
                await broadcast_telemetry(station_id, reading)
                
        except Exception as e:
            print(f"Telemetry simulator error: {e}")
            
        await asyncio.sleep(settings.TELEMETRY_INTERVAL_SECONDS)
